# Options
cask_args appdir: '~/Applications', require_sha: true

# Taps
tap "buo/cask-upgrade"

brew "asdf"															# version manager
brew "atuin"														# history
brew "bat"															# cat replacement
# brew "bazelisk"													# bazel
brew "bottom"														# top replacement
# brew "carbonyl"													# browser
brew "coreutils"												# coreutils
brew "direnv"														# env management
brew "dust"															# du replacement
brew "eza"															# ls replacement
brew "fd"																# find replacement
brew "fzf"															# fuzzy finder
brew "gh"																# github cli
brew "git"															# git
brew "git-extras"												# git
brew "git-lfs"													# git-lfs
brew "git-svn"													# git svn
brew "gnupg"														# gpg
brew "grep"															# grep
brew "htop"															# top replacement
brew "httpie"														# curl replacement
brew "hyperfine"												# time replacement
brew "jq"																# json parser
brew "lazygit"													# git ui
brew "magic-wormhole"										# file transfer
brew "mas"															# mac app store cli
brew "neo4j"														# graph database
brew "neovim"														# vim replacement
brew "openssl"													# openssl
brew "procs"														# ps replacement
brew "protobuf"													# protocol buffers
brew "ripgrep"													# grep replacement
brew "scc"															# count lines of code
brew "sd"																# sed replacement
brew "starship"													# prompt
brew "stow"															# symlink manager
brew "subversion"												# subversion
brew "tldr"															# man replacement
# brew "tmux"															# terminal multiplexer
brew "tokei"														# cloc replacement
brew "xh"																# curl replacement
brew "yq"																# yaml parser
# brew "zellij"														# terminal multiplexer
brew "zoxide"														# zsh plugin
brew "lf"
brew "mutt"
brew "zoxide"
brew "mole"

cask "arc"															# browser
cask "1password"												# password manager
cask "1password-cli"
cask "bruno"														# postman alternative
cask "docker"														# container manager
cask "figma"														# design
cask "font-fira-code-nerd-font"					# font
cask "font-jetbrains-mono-nerd-font"		# font
cask "font-sauce-code-pro-nerd-font"		# font
cask "ghostty"
cask "keyclu"
cask "kreya"														# postman for rpc
cask "notion"														# notes
cask "proxyman"
cask "raycast"													# spotlight
cask "slack"														# communication
cask "sloth"														# network monitor
cask "telegram"													# telegram client
cask "visual-studio-code"								# editor
cask "vlc"															# media player
cask "whatsapp"													# whatsapp client
cask "zed"															# editor
