import = [
	"~/.config/alacritty/catppuccin/catppuccin-mocha.toml",
]

live_config_reload = true

[colors]
draw_bold_text_with_bright_colors = true

[cursor]
style = "Block"
unfocused_hollow = true

[env]
TERM = "xterm-256color"

[keyboard]
bindings = [
	{ key = "H", mods = "Command", action = "Hide" },
	{ key = "Q", mods = "Command", action = "Quit" },
	{ key = "V", mods = "Command", action = "Paste" },
	{ key = "C", mods = "Command", action = "Copy" },
	{ key = "Key0", mods = "Command", action = "ResetFontSize" },
	{ key = "Equals", mods = "Command", action = "IncreaseFontSize" },
	{ key = "Minus", mods = "Command", action = "DecreaseFontSize" },
	{ key = "K", mods = "Command", command = { program = "/opt/homebrew/bin/zellij", args = [
		"action",
		"clear",
	] } },
	{ key = "F", mods = "Command", command = { program = "/opt/homebrew/bin/zellij", args = [
		"action",
		"edit-scrollback",
	] } },
	{ key = "LBracket", mods = "Command", command = { program = "/opt/homebrew/bin/zellij", args = [
		"action",
		"focus-previous-pane",
	] } },
	{ key = "RBracket", mods = "Command", command = { program = "/opt/homebrew/bin/zellij", args = [
		"action",
		"focus-next-pane",
	] } },
	{ key = "T", mods = "Alt", command = { program = "/opt/homebrew/bin/zellij", args = [
		"action",
		"new-pane",
	] } },
	{ key = "D", mods = "Command", command = { program = "/opt/homebrew/bin/zellij", args = [
		"action",
		"new-pane",
	] } },
	{ key = "W", mods = "Alt", command = { program = "/opt/homebrew/bin/zellij", args = [
		"action",
		"close-pane",
	] } },
	{ key = "Return", mods = "Command|Shift", command = { program = "/opt/homebrew/bin/zellij", args = [
		"action",
		"toggle-fullscreen",
	] } },
	{ key = "T", mods = "Command", command = { program = "/opt/homebrew/bin/zellij", args = [
		"action",
		"new-tab",
	] } },
	{ key = "W", mods = "Command", command = { program = "/opt/homebrew/bin/zellij", args = [
		"action",
		"close-pane",
	] } },
	{ key = "Key1", mods = "Command", command = { program = "/opt/homebrew/bin/zellij", args = [
		"action",
		"go-to-tab",
		"1",
	] } },
	{ key = "Key2", mods = "Command", command = { program = "/opt/homebrew/bin/zellij", args = [
		"action",
		"go-to-tab",
		"2",
	] } },
	{ key = "Key3", mods = "Command", command = { program = "/opt/homebrew/bin/zellij", args = [
		"action",
		"go-to-tab",
		"3",
	] } },
	{ key = "Key4", mods = "Command", command = { program = "/opt/homebrew/bin/zellij", args = [
		"action",
		"go-to-tab",
		"4",
	] } },
	{ key = "Key5", mods = "Command", command = { program = "/opt/homebrew/bin/zellij", args = [
		"action",
		"go-to-tab",
		"5",
	] } },
	{ key = "Key6", mods = "Command", command = { program = "/opt/homebrew/bin/zellij", args = [
		"action",
		"go-to-tab",
		"6",
	] } },
	{ key = "Key7", mods = "Command", command = { program = "/opt/homebrew/bin/zellij", args = [
		"action",
		"go-to-tab",
		"7",
	] } },
	{ key = "Key8", mods = "Command", command = { program = "/opt/homebrew/bin/zellij", args = [
		"action",
		"go-to-tab",
		"8",
	] } },
	{ key = "Key9", mods = "Command", command = { program = "/opt/homebrew/bin/zellij", args = [
		"action",
		"go-to-tab",
		"9",
	] } },
]

[scrolling]
history = 10000
multiplier = 10

[selection]
save_to_clipboard = true
semantic_escape_chars = "|:\"' {}()[]<>"

[shell]
args = ["-l", "-c", "zellij attach --index 0 || zellij"]
program = "/bin/zsh"

[window]
decorations = "buttonless"
dynamic_padding = false
opacity = 1.0
option_as_alt = "Both"

[window.padding]
x = 10
y = 10

[font]
normal = { family = "CartographCF Nerd Font", style = "Regular" }
bold = { family = "CartographCF Nerd Font", style = "Bold" }
italic = { family = "CartographCF Nerd Font", style = "Italic" }
bold_italic = { family = "CartographCF Nerd Font", style = "Bold Italic" }
size = 16.0
