tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
# tap "buo/cask-upgrade"
# tap "homebrew/cask-fonts"

berw "ripgrep"
brew "asdf"
brew "bazelisk"
brew "browsh"
brew "gh"
brew "git-extras"
brew "git"
brew "lazygit"
brew "magic-wormhole"
brew "mas"
brew "neo4j"
brew "neovim"
brew "protobuf"
brew "qmk"
brew "ranger"
brew "stow"
brew "terraform"
brew "tmux"
brew "tokei"

cask "1password"
cask "bloomrpc"
cask "docker"
cask "ferdium"
cask "figma"
cask "fork"
cask "iterm2"
cask "notion"
cask "qmk-toolbox"
cask "rectangle"
cask "slack"
cask "visual-studio-code"
cask "vlc"
